---

- name: Basic update for Debian Servers
  hosts: "{{ target }}"

  tasks:
    - name: Check if server has unifi
      command: dpkg-query -l unifi
      register: package_check_unifi
      ignore_errors: yes

    - name: Update repositories cache (apt update)
      become: yes
      apt:
        update_cache: yes

    - name: Upgrading (apt upgrade) with unifi
      become: yes
      when: package_check_unifi is succeeded
      shell: echo "unifi unifi/has_backup boolean true" | debconf-set-selections && DEBIAN_FRONTEND=noninteractive apt-get install --only-upgrade unifi && service unifi restart
    
    - name: Upgrading (apt upgrade)
      become: yes
      apt:
        upgrade: 'yes'

    - name: Autoclean (apt autoclean)
      become: yes
      apt:
        autoclean: yes

    - name: Autoremove (apt autoremove)
      become: yes
      apt:
        autoremove: yes